image: maven:latest
variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

stages:
    - build
    - package
    - deploy

cache:
  paths:
    - .m2/repository
    - target

build_job:
  stage: build
  tags:
    - docker 
  script: 
    - echo "Compiling OpenCreative+, please wait..."
    - "mvn compile"

package_job:
  stage: package
  tags:
    - docker 
  script: 
    - echo "Saving OpenCreative+ into file, please wait..."
    - "mvn package"

Deploy_job:
  stage: deploy
  tags:
    - docker 
  script: 
    - echo "Deploying..."