#
# OpenCreative+ 5.0 - Things will be different.
# (C) McChicken Studio 2017-2025.
#

#
# Pre-release version!
#
#   Config can be changed in next updates,
#   please always check update notes before
#   updating a plugin to next version.
#

#
# This plugin allows players to create their worlds,
# where they can build, play and even make a code.
#
# Commands:
#
#  /spawn - Teleports to spawn world.
#  /locate [Player] - Displays world info, where player currently plays.
#  /join [ID] - Connects player to world with specified ID.
#  /games - Opens worlds browser
#  /cc    - Sends message to creative (global) chat for all players.
#    /cc off - Turns off creative chat for player.
#    /cc on  - Turns on creative chat for player.
#
#  /world - Opens world's settings or displays world's info
#    /world info - Displays world's info.
#    /world delete - Deletes world.
#    /world deletemobs - Removes mobs.
#  /ad - Advertises world in chat for all players.
#  /build - Changes world's mode to Build, disables PvP,
#           and gives Creative mode to world owner and builders.
#  /play  - Changes world's mode to Play, enables PvP out of spawn area,
#           and executes code made in developer mode.
#  /dev   - Connects player to developer world, where he can create
#           a code for world, that will be executed in Play mode.
#  /environment - Opens environment settings. (for world owners, world developers)
#    /env vars list - Displays list of variables.
#    /env vars size - Displays total amount of variables.
#    /env debug - Debug mode of code.
#    /env barrel - Toggles chests or barrels in dev world.
#    /env event [Material] - Changes material for event section in dev world.
#    /env action [Material] - Changes material for action section in dev world.
#    /env floor [Material] - Changes material for floor in dev world.
#  /like - Changes world's reputation by +1
#  /dislike - Changes world's reputation by -1
#
#  /give [Player] [Material] [Amount] - Gives item.               (for world owners, world developers or builders)
#  /tp [Player] (player) - Teleports to player.                   (for world owners, world developers or builders)
#  /gamemode [Gamemode] (player) - Changes player's gamemode.     (for world owners, world developers or builders)
#  /playsound [Player] [Sound] [Volume] [Pitch] - Plays a sound.  (for world owners, world developers or builders)
#  /time set [Time] - Changes world's time.                       (for world owners, world developers or builders)
#  /weather [Sun/Storm] - Changes world's weather.                (for world owners, world developers or builders)
#  /stopsound [Player] - Stops sounds.                            (for world owners, world developers or builders)
#
#  /creative - Opens menu of plugin info.
#    /creative reload - Reloads config.
#    /creative list - Displays list of loaded worlds.
#    /creative deprecated - Displays list of old worlds, which have owner,
#                           that last joined server 1 month ago.
#    /creative corrupted - Displays list of worlds, that lost settings.yml.
#    /creative load [ID] - Loads specified world.
#    /creative unload [ID] - Unloads specified world.
#    /creative maintenance - Maintenance mode settings (start, end).
#    /creative creative-chat - Creative Chat settings (on, off)
#

#
# Powered by Paper API.
# Licensed under GNU GPL v3.
# Additional features by: Vault, ProtocolLib, PlaceholderAPI, LibsDisguises.
#
# Hangar: https://hangar.papermc.io/mcchickenstudio/OpenCreative
# Source code: https://gitlab.com/eagles-creative/opencreative
# Discord: https://discord.gg/sSFCXUeq63
#

version: 5.0
last-world-id: 0
hide-from-tab: spectator # Hides players, that aren't in same world: spectator - Transparent nickname (requires ProtocolLib), full - Full hide from tab list, none - Not hide.

lobby:
  #
  # Lobby is a world, where player teleports on server join,
  # or on command type: /lobby, /hub, /spawn. It gives player
  # items for opening menus. To change spawn location use
  # /setworldspawn command.
  #
  world: "world"
  sound:
    name: "music_disc.creator_music_box"
    pitch: 0.7

recommended-worlds: [1,2,3,4,5] # List of featured worlds in /games, type world number IDs here.

execute-console-commands: # These commands will be executed on some Creative events
  creative-chat: [] # Remove [] if there are some commands
    #- "discordsrv broadcast Creative Chat | %player%: %message%"

allowed-links:
  resource-pack:
    - "dropbox.com"
    - "drive.google.com"

messages:
  locale: en # Supported: en, ru - Для русского языка: ru
  branding: "<white>Open<gradient:#dbdbdb:#ffd4c2>Creative</gradient><green>+"
  prefix: "&6 Worlds &8| &f"
  cc-prefix: "&6 Creative Chat &8| &7"
  cc-chat: "%cc-prefix%&7%player%&7: %message%" # You can use PAPI placeholders here
  world-chat: "&7 %player% &8» &f%message%" # and here
  version: "&f \n &fPowered by Open&7Creative&b+ &3%version%\n &f%codename% \n \n &fContibutors: &7McChicken Team\n &fTranslators: &7initzero, Nagibator6000Lol \n \n &cMcChicken Studio 2017-2025\n &c"
groups:
  #
  # Groups are made for specifying players permissions,
  # like world size, world limits, worlds amount.
  #
  default: # default - by default for any player, no permissions required
    cooldowns:
      generic-command: 5 # /play, /build, /games
      advertisement: 120 # /ad
      creative-chat: 10 # /cc
      world-chat: 2 # chat in world
    creating-world:
      limit: 2
    world:
      size: 25
      limits:
        #
        # Limits for world, that player created.
        #
        executor-calls: 100 # limit of executor calls
        entities-amount: 50 # limit for spawned entities in world
        modifying-blocks: 5000 # limit for changing blocks with world actions per second
        redstone-changes: 100 # limit for redstone operations in world
        opening-inventories: 5 # limit for opening inventories per 5 seconds for preventing anti-exit
        variables-amount: 50 # limit for amount of all variables in world (saved, global, local)
        scoreboards-amount: 50 # limit for amount of all scoreboards
        bossbars-amount: 10 # limit for amount of all bossbars
        coding-platforms: 4 # limit for coding platforms
      per-player-limit-modifiers:
        #
        # When player joins a world or leaves from world,
        # this will increase or decrease limits values.
        #
        executor-calls: 100
        entities-amount: 50
        modifying-blocks: 0
        redstone-changes: 20
        opening-inventories: 5
        variables-amount: 50
        scoreboards-amount: 3
        bossbars-amount: 3
      build-permissions: # Permissions will be given when player types /build command
        - "headdb.open"
        - "worldedit.wand"
        # If you want to add WorldEdit permissions please turn off
        # region-restrictions in WorldEdit/config.yml to make //set working
        #- "worldedit.region.set"
      play-permissions: # Permissions will be given when player types /play command
        - "headdb.open"
      dev-permissions: # Permissions will be given when player types /dev command
        - "headdb.open"
        - "essentials.itemname"
  premium:
    permission: "opencreative.group.premium"
    cooldowns:
      generic-command: 3
      advertisement: 100
      creative-chat: 4
      world-chat: 1
    creating-world:
      limit: 4
    world:
      size: 50
      limits:
        executor-calls: 120
        entities-amount: 200
        modifying-blocks: 7500
        redstone-changes: 200
        opening-inventories: 5
        variables-amount: 500
        scoreboards-amount: 50
        bossbars-amount: 10
        coding-platforms: 4
      per-player-limit-modifiers:
        executor-calls: 30
        entities-amount: 50
        modifying-blocks: 0
        redstone-changes: 20
        opening-inventories: 5
        variables-amount: 50
        scoreboards-amount: 10
        bossbars-amount: 10
      build-permissions:
        - "headdb.open"
        - "worldedit.wand"
        #- "worldedit.region.set"
        #- "worldedit.region.replace"
      play-permissions:
        - "headdb.open"
      dev-permissions:
        - "headdb.open"
        - "essentials.itemname"

#
# Maintenance mode unloads all worlds and
# prevents players without admin permissions
# from loading or creating worlds.
#
# /creative maintenance start 30
# /creative maintenance end
#
maintenance: false
#
# In Debug mode OpenCreative+ will send some
# information about plugin's work and state.
# Not useful, if you're not developing OC+.
#
debug: false
